/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as CheckRouteImport } from './routes/check'
import { Route as ExamRouteImport } from './routes/exam'
import { Route as SubmittedRouteImport } from './routes/submitted'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminParticipantsRouteImport } from './routes/admin/participants'
import { Route as AdminQuestionsRouteImport } from './routes/admin/questions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamRoute = ExamRouteImport.update({
  id: '/exam',
  path: '/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmittedRoute = SubmittedRouteImport.update({
  id: '/submitted',
  path: '/submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/admin/participants',
  path: '/admin/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/check': typeof CheckRoute
  '/exam': typeof ExamRoute
  '/submitted': typeof SubmittedRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/check': typeof CheckRoute
  '/exam': typeof ExamRoute
  '/submitted': typeof SubmittedRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blocked': typeof BlockedRoute
  '/check': typeof CheckRoute
  '/exam': typeof ExamRoute
  '/submitted': typeof SubmittedRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blocked'
    | '/check'
    | '/exam'
    | '/submitted'
    | '/terms'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blocked'
    | '/check'
    | '/exam'
    | '/submitted'
    | '/terms'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/blocked'
    | '/check'
    | '/exam'
    | '/submitted'
    | '/terms'
    | '/admin/login'
    | '/admin/participants'
    | '/admin/questions'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlockedRoute: typeof BlockedRoute
  CheckRoute: typeof CheckRoute
  ExamRoute: typeof ExamRoute
  SubmittedRoute: typeof SubmittedRoute
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam': {
      id: '/exam'
      path: '/exam'
      fullPath: '/exam'
      preLoaderRoute: typeof ExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submitted': {
      id: '/submitted'
      path: '/submitted'
      fullPath: '/submitted'
      preLoaderRoute: typeof SubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/admin/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlockedRoute: BlockedRoute,
  CheckRoute: CheckRoute,
  ExamRoute: ExamRoute,
  SubmittedRoute: SubmittedRoute,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
